package ch.epfl.gameboj.component.cpu;

// This is version 3 of Opcode.java, with correct values for additionalCycles.

public enum Opcode {
    // Direct (non-prefixed) opcodes
    ADD_A_B(Kind.DIRECT, Family.ADD_A_R8, 0x80, 1, 1 ,(int...parameters)->"ADD A,B"),
    ADD_A_C(Kind.DIRECT, Family.ADD_A_R8, 0x81, 1, 1,(int...parameters)->"ADD A,C"),
    ADD_A_D(Kind.DIRECT, Family.ADD_A_R8, 0x82, 1, 1,(int...parameters)->"ADD A,D"),
    ADD_A_E(Kind.DIRECT, Family.ADD_A_R8, 0x83, 1, 1,(int...parameters)->"ADD A,E"),
    ADD_A_H(Kind.DIRECT, Family.ADD_A_R8, 0x84, 1, 1,(int...parameters)->"ADD A,H"),
    ADD_A_L(Kind.DIRECT, Family.ADD_A_R8, 0x85, 1, 1,(int...parameters)->"ADD A,L"),
    ADD_A_A(Kind.DIRECT, Family.ADD_A_R8, 0x87, 1, 1,(int...parameters)->"ADD A,A"),
    ADC_A_B(Kind.DIRECT, Family.ADD_A_R8, 0x88, 1, 1,(int...parameters)->"ADC A,B"),
    ADC_A_C(Kind.DIRECT, Family.ADD_A_R8, 0x89, 1, 1,(int...parameters)->"ADC A,C"),
    ADC_A_D(Kind.DIRECT, Family.ADD_A_R8, 0x8A, 1, 1,(int...parameters)->"ADC A,D"),
    ADC_A_E(Kind.DIRECT, Family.ADD_A_R8, 0x8B, 1, 1,(int...parameters)->"ADC A,E"),
    ADC_A_H(Kind.DIRECT, Family.ADD_A_R8, 0x8C, 1, 1,(int...parameters)->"ADC A,H"),
    ADC_A_L(Kind.DIRECT, Family.ADD_A_R8, 0x8D, 1, 1,(int...parameters)->"ADC A,L"),
    ADC_A_A(Kind.DIRECT, Family.ADD_A_R8, 0x8F, 1, 1,(int...parameters)->"ADC A,A"),
    SUB_A_B(Kind.DIRECT, Family.SUB_A_R8, 0x90, 1, 1,(int...parameters)->"SUB A,B"),
    SUB_A_C(Kind.DIRECT, Family.SUB_A_R8, 0x91, 1, 1,(int...parameters)->"SUB A,C"),
    SUB_A_D(Kind.DIRECT, Family.SUB_A_R8, 0x92, 1, 1,(int...parameters)->"SUB A,D"),
    SUB_A_E(Kind.DIRECT, Family.SUB_A_R8, 0x93, 1, 1,(int...parameters)->"SUB A,E"),
    SUB_A_H(Kind.DIRECT, Family.SUB_A_R8, 0x94, 1, 1,(int...parameters)->"SUB A,H"),
    SUB_A_L(Kind.DIRECT, Family.SUB_A_R8, 0x95, 1, 1,(int...parameters)->"SUB A,L"),
    SUB_A_A(Kind.DIRECT, Family.SUB_A_R8, 0x97, 1, 1,(int...parameters)->"SUB A,A"),
    SBC_A_B(Kind.DIRECT, Family.SUB_A_R8, 0x98, 1, 1,(int...parameters)->"SBC A,B"),
    SBC_A_C(Kind.DIRECT, Family.SUB_A_R8, 0x99, 1, 1,(int...parameters)->"SBC A,C"),
    SBC_A_D(Kind.DIRECT, Family.SUB_A_R8, 0x9A, 1, 1,(int...parameters)->"SBC A,D"),
    SBC_A_E(Kind.DIRECT, Family.SUB_A_R8, 0x9B, 1, 1,(int...parameters)->"SBC A,E"),
    SBC_A_H(Kind.DIRECT, Family.SUB_A_R8, 0x9C, 1, 1,(int...parameters)->"SBC A,H"),
    SBC_A_L(Kind.DIRECT, Family.SUB_A_R8, 0x9D, 1, 1,(int...parameters)->"SBC A,L"),
    SBC_A_A(Kind.DIRECT, Family.SUB_A_R8, 0x9F, 1, 1,(int...parameters)->"SBC A,A"),
    AND_A_B(Kind.DIRECT, Family.AND_A_R8, 0xA0, 1, 1,(int...parameters)->"AND A,B"),
    AND_A_C(Kind.DIRECT, Family.AND_A_R8, 0xA1, 1, 1,(int...parameters)->"AND A,C"),
    AND_A_D(Kind.DIRECT, Family.AND_A_R8, 0xA2, 1, 1,(int...parameters)->"AND A,D"),
    AND_A_E(Kind.DIRECT, Family.AND_A_R8, 0xA3, 1, 1,(int...parameters)->"AND A,E"),
    AND_A_H(Kind.DIRECT, Family.AND_A_R8, 0xA4, 1, 1,(int...parameters)->"AND A,H"),
    AND_A_L(Kind.DIRECT, Family.AND_A_R8, 0xA5, 1, 1,(int...parameters)->"AND A,L"),
    AND_A_A(Kind.DIRECT, Family.AND_A_R8, 0xA7, 1, 1,(int...parameters)->"AND A,A"),
    OR_A_B(Kind.DIRECT, Family.OR_A_R8, 0xB0, 1, 1,(int...parameters)->"OR A,B"),
    OR_A_C(Kind.DIRECT, Family.OR_A_R8, 0xB1, 1, 1,(int...parameters)->"OR A,C"),
    OR_A_D(Kind.DIRECT, Family.OR_A_R8, 0xB2, 1, 1,(int...parameters)->"OR A,D"),
    OR_A_E(Kind.DIRECT, Family.OR_A_R8, 0xB3, 1, 1,(int...parameters)->"OR A,E"),
    OR_A_H(Kind.DIRECT, Family.OR_A_R8, 0xB4, 1, 1,(int...parameters)->"OR A,H"),
    OR_A_L(Kind.DIRECT, Family.OR_A_R8, 0xB5, 1, 1,(int...parameters)->"OR A,L"),
    OR_A_A(Kind.DIRECT, Family.OR_A_R8, 0xB7, 1, 1,(int...parameters)->"OR A,A"),
    XOR_A_B(Kind.DIRECT, Family.XOR_A_R8, 0xA8, 1, 1,(int...parameters)->"XOR A,B"),
    XOR_A_C(Kind.DIRECT, Family.XOR_A_R8, 0xA9, 1, 1,(int...parameters)->"XOR A,C"),
    XOR_A_D(Kind.DIRECT, Family.XOR_A_R8, 0xAA, 1, 1,(int...parameters)->"XOR A,D"),
    XOR_A_E(Kind.DIRECT, Family.XOR_A_R8, 0xAB, 1, 1,(int...parameters)->"XOR A,E"),
    XOR_A_H(Kind.DIRECT, Family.XOR_A_R8, 0xAC, 1, 1,(int...parameters)->"XOR A,H"),
    XOR_A_L(Kind.DIRECT, Family.XOR_A_R8, 0xAD, 1, 1,(int...parameters)->"XOR A,L"),
    XOR_A_A(Kind.DIRECT, Family.XOR_A_R8, 0xAF, 1, 1,(int...parameters)->"XOR A,A"),
    CP_A_B(Kind.DIRECT, Family.CP_A_R8, 0xB8, 1, 1,(int...parameters)->"XOR A,B"),
    CP_A_C(Kind.DIRECT, Family.CP_A_R8, 0xB9, 1, 1,(int...parameters)->"XOR A,C"),
    CP_A_D(Kind.DIRECT, Family.CP_A_R8, 0xBA, 1, 1,(int...parameters)->"XOR A,D"),
    CP_A_E(Kind.DIRECT, Family.CP_A_R8, 0xBB, 1, 1,(int...parameters)->"CP A,E"),
    CP_A_H(Kind.DIRECT, Family.CP_A_R8, 0xBC, 1, 1,(int...parameters)->"CP A,H"),
    CP_A_L(Kind.DIRECT, Family.CP_A_R8, 0xBD, 1, 1,(int...parameters)->"CP A,L"),
    CP_A_A(Kind.DIRECT, Family.CP_A_R8, 0xBF, 1, 1,(int...parameters)->"CP A,A"),
    ADD_A_N8(Kind.DIRECT, Family.ADD_A_N8, 0xC6, 2, 2,(int...parameters)-> "ADD A,$"+Integer.toHexString(parameters[0])),
    ADC_A_N8(Kind.DIRECT, Family.ADD_A_N8, 0xCE, 2, 2,(int...parameters)->"ADC A,$"+Integer.toHexString(parameters[0])),
    SUB_A_N8(Kind.DIRECT, Family.SUB_A_N8, 0xD6, 2, 2,(int...parameters)->"SUB A,$"+Integer.toHexString(parameters[0])),
    SBC_A_N8(Kind.DIRECT, Family.SUB_A_N8, 0xDE, 2, 2,(int...parameters)->"SBC A,$"+Integer.toHexString(parameters[0])),
    AND_A_N8(Kind.DIRECT, Family.AND_A_N8, 0xE6, 2, 2,(int...parameters)->"AND A,$"+Integer.toHexString(parameters[0])),
    OR_A_N8(Kind.DIRECT, Family.OR_A_N8, 0xF6, 2, 2,(int...parameters)->"OR A,$"+Integer.toHexString(parameters[0])),
    XOR_A_N8(Kind.DIRECT, Family.XOR_A_N8, 0xEE, 2, 2,(int...parameters)->"XOR A,$"+Integer.toHexString(parameters[0])),
    CP_A_N8(Kind.DIRECT, Family.CP_A_N8, 0xFE, 2, 2,(int...parameters)->"CP A,$"+Integer.toHexString(parameters[0])),
    ADD_A_HLR(Kind.DIRECT, Family.ADD_A_HLR, 0x86, 1, 2,(int...parameters)->"ADD A,[HL]"),
    ADC_A_HLR(Kind.DIRECT, Family.ADD_A_HLR, 0x8E, 1, 2,(int...parameters)->"ADC A,[HL]"),
    SUB_A_HLR(Kind.DIRECT, Family.SUB_A_HLR, 0x96, 1, 2,(int...parameters)->"SUB A,[HL]"),
    SBC_A_HLR(Kind.DIRECT, Family.SUB_A_HLR, 0x9E, 1, 2,(int...parameters)->"SBC A,[HL]"),
    AND_A_HLR(Kind.DIRECT, Family.AND_A_HLR, 0xA6, 1, 2,(int...parameters)->"AND A,[HL]"),
    OR_A_HLR(Kind.DIRECT, Family.OR_A_HLR, 0xB6, 1, 2,(int...parameters)->"OR A,[HL]"),
    XOR_A_HLR(Kind.DIRECT, Family.XOR_A_HLR, 0xAE, 1, 2,(int...parameters)->"XOR A,[HL]"),
    CP_A_HLR(Kind.DIRECT, Family.CP_A_HLR, 0xBE, 1, 2,(int...parameters)->"CP A,[HL]"),
    PUSH_BC(Kind.DIRECT, Family.PUSH_R16, 0xC5, 1, 4,(int...parameters)->"PUSH BC"),
    PUSH_DE(Kind.DIRECT, Family.PUSH_R16, 0xD5, 1, 4,(int...parameters)->"PUSH DE"),
    PUSH_HL(Kind.DIRECT, Family.PUSH_R16, 0xE5, 1, 4,(int...parameters)->"PUSH HL"),
    PUSH_AF(Kind.DIRECT, Family.PUSH_R16, 0xF5, 1, 4,(int...parameters)->"PUSH AF"),
    POP_BC(Kind.DIRECT, Family.POP_R16, 0xC1, 1, 3, (int...parameters)->"POP BC"),
    POP_DE(Kind.DIRECT, Family.POP_R16, 0xD1, 1, 3,(int...parameters)->"POP DE"),
    POP_HL(Kind.DIRECT, Family.POP_R16, 0xE1, 1, 3,(int...parameters)->"POP HL"),
    POP_AF(Kind.DIRECT, Family.POP_R16, 0xF1, 1, 3,(int...parameters)->"POP AF"),
    INC_B(Kind.DIRECT, Family.INC_R8, 0x04, 1, 1,(int...parameters)->"INC B"),
    INC_C(Kind.DIRECT, Family.INC_R8, 0x0C, 1, 1,(int...parameters)->"INC C"),
    INC_D(Kind.DIRECT, Family.INC_R8, 0x14, 1, 1,(int...parameters)->"INC D"),
    INC_E(Kind.DIRECT, Family.INC_R8, 0x1C, 1, 1,(int...parameters)->"INC E"),
    INC_H(Kind.DIRECT, Family.INC_R8, 0x24, 1, 1,(int...parameters)->"INC H"),
    INC_L(Kind.DIRECT, Family.INC_R8, 0x2C, 1, 1,(int...parameters)->"INC L"),
    INC_A(Kind.DIRECT, Family.INC_R8, 0x3C, 1, 1,(int...parameters)->"INC A"),
    DEC_B(Kind.DIRECT, Family.DEC_R8, 0x05, 1, 1,(int...parameters)->"DEC B"),
    DEC_C(Kind.DIRECT, Family.DEC_R8, 0x0D, 1, 1,(int...parameters)->"DEC C"),
    DEC_D(Kind.DIRECT, Family.DEC_R8, 0x15, 1, 1,(int...parameters)->"DEC D"),
    DEC_E(Kind.DIRECT, Family.DEC_R8, 0x1D, 1, 1,(int...parameters)->"DEC E"),
    DEC_H(Kind.DIRECT, Family.DEC_R8, 0x25, 1, 1,(int...parameters)->"DEC H"),
    DEC_L(Kind.DIRECT, Family.DEC_R8, 0x2D, 1, 1,(int...parameters)->"DEC L"),
    DEC_A(Kind.DIRECT, Family.DEC_R8, 0x3D, 1, 1,(int...parameters)->"DEC A"),
    INC_BC(Kind.DIRECT, Family.INC_R16SP, 0x03, 1, 2,(int...parameters)->"INC BC"),
    INC_DE(Kind.DIRECT, Family.INC_R16SP, 0x13, 1, 2,(int...parameters)->"INC DE"),
    INC_HL(Kind.DIRECT, Family.INC_R16SP, 0x23, 1, 2,(int...parameters)->"INC HL"),
    INC_SP(Kind.DIRECT, Family.INC_R16SP, 0x33, 1, 2,(int...parameters)->"INC SP"),
    DEC_BC(Kind.DIRECT, Family.DEC_R16SP, 0x0B, 1, 2,(int...parameters)->"DEC BC"),
    DEC_DE(Kind.DIRECT, Family.DEC_R16SP, 0x1B, 1, 2,(int...parameters)->"DEC DE"),
    DEC_HL(Kind.DIRECT, Family.DEC_R16SP, 0x2B, 1, 2,(int...parameters)->"DEC HL"),
    DEC_SP(Kind.DIRECT, Family.DEC_R16SP, 0x3B, 1, 2,(int...parameters)->"DEC SP"),
    INC_HLR(Kind.DIRECT, Family.INC_HLR, 0x34, 1, 3,(int...parameters)->"INC [HL]"),
    DEC_HLR(Kind.DIRECT, Family.DEC_HLR, 0x35, 1, 3,(int...parameters)->"DEC [HL]"),
    RLCA(Kind.DIRECT, Family.ROTCA, 0x07, 1, 1,(int...parameters)->"RLCA"),
    RRCA(Kind.DIRECT, Family.ROTCA, 0x0F, 1, 1,(int...parameters)->"RRCA"),
    RLA(Kind.DIRECT, Family.ROTA, 0x17, 1, 1,(int...parameters)->"RLA"),
    RRA(Kind.DIRECT, Family.ROTA, 0x1F, 1, 1,(int...parameters)->"RRA"),
    LD_B_B(Kind.DIRECT, Family.NOP, 0x40, 1, 1,(int...parameters)->"LD B,B"),
    LD_B_C(Kind.DIRECT, Family.LD_R8_R8, 0x41, 1, 1,(int...parameters)->"LD B,C"),
    LD_B_D(Kind.DIRECT, Family.LD_R8_R8, 0x42, 1, 1,(int...parameters)->"LD B,D"),
    LD_B_E(Kind.DIRECT, Family.LD_R8_R8, 0x43, 1, 1,(int...parameters)->"LD B,E"),
    LD_B_H(Kind.DIRECT, Family.LD_R8_R8, 0x44, 1, 1,(int...parameters)->"LD B,H"),
    LD_B_L(Kind.DIRECT, Family.LD_R8_R8, 0x45, 1, 1,(int...parameters)->"LD B,L"),
    LD_B_A(Kind.DIRECT, Family.LD_R8_R8, 0x47, 1, 1,(int...parameters)->"LD B,A"),
    LD_C_B(Kind.DIRECT, Family.LD_R8_R8, 0x48, 1, 1,(int...parameters)->"LD C,B"),
    LD_C_C(Kind.DIRECT, Family.NOP, 0x49, 1, 1,(int...parameters)->"LD C,C"),
    LD_C_D(Kind.DIRECT, Family.LD_R8_R8, 0x4A, 1, 1,(int...parameters)->"LD C,D"),
    LD_C_E(Kind.DIRECT, Family.LD_R8_R8, 0x4B, 1, 1,(int...parameters)->"LD C,E"),
    LD_C_H(Kind.DIRECT, Family.LD_R8_R8, 0x4C, 1, 1,(int...parameters)->"LD C,H"),
    LD_C_L(Kind.DIRECT, Family.LD_R8_R8, 0x4D, 1, 1,(int...parameters)->"LD C,L"),
    LD_C_A(Kind.DIRECT, Family.LD_R8_R8, 0x4F, 1, 1,(int...parameters)->"LD C,A"),
    LD_D_B(Kind.DIRECT, Family.LD_R8_R8, 0x50, 1, 1,(int...parameters)->"LD D,B"),
    LD_D_C(Kind.DIRECT, Family.LD_R8_R8, 0x51, 1, 1,(int...parameters)->"LD D,C"),
    LD_D_D(Kind.DIRECT, Family.NOP, 0x52, 1, 1,(int...parameters)->"LD D,D"),
    LD_D_E(Kind.DIRECT, Family.LD_R8_R8, 0x53, 1, 1,(int...parameters)->"LD D,E"),
    LD_D_H(Kind.DIRECT, Family.LD_R8_R8, 0x54, 1, 1,(int...parameters)->"LD D,H"),
    LD_D_L(Kind.DIRECT, Family.LD_R8_R8, 0x55, 1, 1,(int...parameters)->"LD D,L"),
    LD_D_A(Kind.DIRECT, Family.LD_R8_R8, 0x57, 1, 1,(int...parameters)->"LD D,A"),
    LD_E_B(Kind.DIRECT, Family.LD_R8_R8, 0x58, 1, 1,(int...parameters)->"LD E,B"),
    LD_E_C(Kind.DIRECT, Family.LD_R8_R8, 0x59, 1, 1,(int...parameters)->"LD E,C"),
    LD_E_D(Kind.DIRECT, Family.LD_R8_R8, 0x5A, 1, 1,(int...parameters)->"LD E,D"),
    LD_E_E(Kind.DIRECT, Family.NOP, 0x5B, 1, 1,(int...parameters)->"LD E,E"),
    LD_E_H(Kind.DIRECT, Family.LD_R8_R8, 0x5C, 1, 1,(int...parameters)->"LD E,H"),
    LD_E_L(Kind.DIRECT, Family.LD_R8_R8, 0x5D, 1, 1,(int...parameters)->"LD E,L"),
    LD_E_A(Kind.DIRECT, Family.LD_R8_R8, 0x5F, 1, 1,(int...parameters)->"LD E,A"),
    LD_H_B(Kind.DIRECT, Family.LD_R8_R8, 0x60, 1, 1,(int...parameters)->"LD H,B"),
    LD_H_C(Kind.DIRECT, Family.LD_R8_R8, 0x61, 1, 1,(int...parameters)->"LD H,C"),
    LD_H_D(Kind.DIRECT, Family.LD_R8_R8, 0x62, 1, 1,(int...parameters)->"LD H,D"),
    LD_H_E(Kind.DIRECT, Family.LD_R8_R8, 0x63, 1, 1,(int...parameters)->"LD H,E"),
    LD_H_H(Kind.DIRECT, Family.NOP, 0x64, 1, 1,(int...parameters)->"LD H,H"),
    LD_H_L(Kind.DIRECT, Family.LD_R8_R8, 0x65, 1, 1,(int...parameters)->"LD H,L"),
    LD_H_A(Kind.DIRECT, Family.LD_R8_R8, 0x67, 1, 1,(int...parameters)->"LD H,A"),
    LD_L_B(Kind.DIRECT, Family.LD_R8_R8, 0x68, 1, 1,(int...parameters)->"LD L,B"),
    LD_L_C(Kind.DIRECT, Family.LD_R8_R8, 0x69, 1, 1,(int...parameters)->"LD L,C"),
    LD_L_D(Kind.DIRECT, Family.LD_R8_R8, 0x6A, 1, 1,(int...parameters)->"LD L,D"),
    LD_L_E(Kind.DIRECT, Family.LD_R8_R8, 0x6B, 1, 1,(int...parameters)->"LD L,E"),
    LD_L_H(Kind.DIRECT, Family.LD_R8_R8, 0x6C, 1, 1,(int...parameters)->"LD L,H"),
    LD_L_L(Kind.DIRECT, Family.NOP, 0x6D, 1, 1,(int...parameters)->"LD L,L"),
    LD_L_A(Kind.DIRECT, Family.LD_R8_R8, 0x6F, 1, 1,(int...parameters)->"LD L,A"),
    LD_A_B(Kind.DIRECT, Family.LD_R8_R8, 0x78, 1, 1,(int...parameters)->"LD A,B"),
    LD_A_C(Kind.DIRECT, Family.LD_R8_R8, 0x79, 1, 1,(int...parameters)->"LD A,C"),
    LD_A_D(Kind.DIRECT, Family.LD_R8_R8, 0x7A, 1, 1,(int...parameters)->"LD A,D"),
    LD_A_E(Kind.DIRECT, Family.LD_R8_R8, 0x7B, 1, 1,(int...parameters)->"LD A,E"),
    LD_A_H(Kind.DIRECT, Family.LD_R8_R8, 0x7C, 1, 1,(int...parameters)->"LD A,H"),
    LD_A_L(Kind.DIRECT, Family.LD_R8_R8, 0x7D, 1, 1,(int...parameters)->"LD A,L"),
    LD_A_A(Kind.DIRECT, Family.NOP, 0x7F, 1, 1,(int...parameters)->"LD A,A"),
    LD_B_N8(Kind.DIRECT, Family.LD_R8_N8, 0x06, 2, 2,(int...parameters)->"LD B,$"+Integer.toHexString(parameters[0])),
    LD_C_N8(Kind.DIRECT, Family.LD_R8_N8, 0x0E, 2, 2,(int...parameters)->"LD C,$"+Integer.toHexString(parameters[0])),
    LD_D_N8(Kind.DIRECT, Family.LD_R8_N8, 0x16, 2, 2,(int...parameters)->"LD D,$"+Integer.toHexString(parameters[0])),
    LD_E_N8(Kind.DIRECT, Family.LD_R8_N8, 0x1E, 2, 2,(int...parameters)->"LD E,$"+Integer.toHexString(parameters[0])),
    LD_H_N8(Kind.DIRECT, Family.LD_R8_N8, 0x26, 2, 2,(int...parameters)->"LD H,$"+Integer.toHexString(parameters[0])),
    LD_L_N8(Kind.DIRECT, Family.LD_R8_N8, 0x2E, 2, 2,(int...parameters)->"LD L,$"+Integer.toHexString(parameters[0])),
    LD_A_N8(Kind.DIRECT, Family.LD_R8_N8, 0x3E, 2, 2,(int...parameters)->"LD A,$"+Integer.toHexString(parameters[0])),
    LD_B_HLR(Kind.DIRECT, Family.LD_R8_HLR, 0x46, 1, 2,(int...parameters)->"LD B,[HL]"),
    LD_C_HLR(Kind.DIRECT, Family.LD_R8_HLR, 0x4E, 1, 2,(int...parameters)->"LD C,[HL]"),
    LD_D_HLR(Kind.DIRECT, Family.LD_R8_HLR, 0x56, 1, 2,(int...parameters)->"LD D,[HL]"),
    LD_E_HLR(Kind.DIRECT, Family.LD_R8_HLR, 0x5E, 1, 2,(int...parameters)->"LD E,[HL]"),
    LD_H_HLR(Kind.DIRECT, Family.LD_R8_HLR, 0x66, 1, 2,(int...parameters)->"LD H,[HL]"),
    LD_L_HLR(Kind.DIRECT, Family.LD_R8_HLR, 0x6E, 1, 2,(int...parameters)->"LD L,[HL]"),
    LD_A_HLR(Kind.DIRECT, Family.LD_R8_HLR, 0x7E, 1, 2,(int...parameters)->"LD A,[HL]"),
    LD_BC_N16(Kind.DIRECT, Family.LD_R16SP_N16, 0x01, 3, 3,(int...parameters)->"LD BC,$"+Integer.toHexString(parameters[0] | (parameters[1]<<Byte.SIZE))),
    LD_DE_N16(Kind.DIRECT, Family.LD_R16SP_N16, 0x11, 3, 3,(int...parameters)->"LD DE,$"+Integer.toHexString(parameters[0] | (parameters[1]<<Byte.SIZE))),
    LD_HL_N16(Kind.DIRECT, Family.LD_R16SP_N16, 0x21, 3, 3,(int...parameters)->"LD HL,$"+Integer.toHexString(parameters[0] | (parameters[1]<<Byte.SIZE))),
    LD_SP_N16(Kind.DIRECT, Family.LD_R16SP_N16, 0x31, 3, 3,(int...parameters)->"LD SP,$"+Integer.toHexString(parameters[0] | (parameters[1]<<Byte.SIZE))),
    LD_HLR_B(Kind.DIRECT, Family.LD_HLR_R8, 0x70, 1, 2,(int...parameters)->"LD [HL],B"),
    LD_HLR_C(Kind.DIRECT, Family.LD_HLR_R8, 0x71, 1, 2,(int...parameters)->"LD [HL],C"),
    LD_HLR_D(Kind.DIRECT, Family.LD_HLR_R8, 0x72, 1, 2,(int...parameters)->"LD [HL],D"),
    LD_HLR_E(Kind.DIRECT, Family.LD_HLR_R8, 0x73, 1, 2,(int...parameters)->"LD [HL],E"),
    LD_HLR_H(Kind.DIRECT, Family.LD_HLR_R8, 0x74, 1, 2,(int...parameters)->"LD [HL],H"),
    LD_HLR_L(Kind.DIRECT, Family.LD_HLR_R8, 0x75, 1, 2,(int...parameters)->"LD [HL],L"),
    LD_HLR_A(Kind.DIRECT, Family.LD_HLR_R8, 0x77, 1, 2,(int...parameters)->"LD [HL],A"),
    ADD_HL_BC(Kind.DIRECT, Family.ADD_HL_R16SP, 0x09, 1, 2,(int...parameters)->"LD HL,BC"),
    ADD_HL_DE(Kind.DIRECT, Family.ADD_HL_R16SP, 0x19, 1, 2,(int...parameters)->"LD HL,DE"),
    ADD_HL_HL(Kind.DIRECT, Family.ADD_HL_R16SP, 0x29, 1, 2,(int...parameters)->"LD HL,HL"),
    ADD_HL_SP(Kind.DIRECT, Family.ADD_HL_R16SP, 0x39, 1, 2,(int...parameters)->"LD HL,SP"),
    JP_NZ_N16(Kind.DIRECT, Family.JP_CC_N16, 0xC2, 3, 3, 1,(int...parameters)->"JP NZ,$"+Integer.toHexString(parameters[0] | (parameters[1]<<Byte.SIZE))),
    JP_Z_N16(Kind.DIRECT, Family.JP_CC_N16, 0xCA, 3, 3, 1,(int...parameters)->"JP Z,$"+Integer.toHexString(parameters[0] | (parameters[1]<<Byte.SIZE))),
    JP_NC_N16(Kind.DIRECT, Family.JP_CC_N16, 0xD2, 3, 3, 1,(int...parameters)->"JP NC,$"+Integer.toHexString(parameters[0] | (parameters[1]<<Byte.SIZE))),
    JP_C_N16(Kind.DIRECT, Family.JP_CC_N16, 0xDA, 3, 3, 1,(int...parameters)->"JP C,$"+Integer.toHexString(parameters[0] | (parameters[1]<<Byte.SIZE))),
    JR_NZ_E8(Kind.DIRECT, Family.JR_CC_E8, 0x20, 2, 2, 1,(int...parameters)->"JR $"+Integer.toHexString(parameters[0])),
    JR_Z_E8(Kind.DIRECT, Family.JR_CC_E8, 0x28, 2, 2, 1,(int...parameters)->"JR Z,$"+Integer.toHexString(parameters[0])),
    JR_NC_E8(Kind.DIRECT, Family.JR_CC_E8, 0x30, 2, 2, 1,(int...parameters)->"JR NC,$"+Integer.toHexString(parameters[0])),
    JR_C_E8(Kind.DIRECT, Family.JR_CC_E8, 0x38, 2, 2, 1,(int...parameters)->"JR C,$"+Integer.toHexString(parameters[0])),
    CALL_NZ_N16(Kind.DIRECT, Family.CALL_CC_N16, 0xC4, 3, 3, 3,(int...parameters)->"CALL NZ,$"+Integer.toHexString(parameters[0] | (parameters[1]<<Byte.SIZE))),
    CALL_Z_N16(Kind.DIRECT, Family.CALL_CC_N16, 0xCC, 3, 3, 3,(int...parameters)->"CALL Z,$"+Integer.toHexString(parameters[0] | (parameters[1]<<Byte.SIZE))),
    CALL_NC_N16(Kind.DIRECT, Family.CALL_CC_N16, 0xD4, 3, 3, 3,(int...parameters)->"CALL NC,$"+Integer.toHexString(parameters[0] | (parameters[1]<<Byte.SIZE))),
    CALL_C_N16(Kind.DIRECT, Family.CALL_CC_N16, 0xDC, 3, 3, 3,(int...parameters)->"CALL C,$"+Integer.toHexString(parameters[0] | (parameters[1]<<Byte.SIZE))),
    RET_NZ(Kind.DIRECT, Family.RET_CC, 0xC0, 1, 2, 3,(int...parameters)->"RST NZ"),
    RET_Z(Kind.DIRECT, Family.RET_CC, 0xC8, 1, 2, 3,(int...parameters)->"RET Z"),
    RET_NC(Kind.DIRECT, Family.RET_CC, 0xD0, 1, 2, 3,(int...parameters)->"RET NC"),
    RET_C(Kind.DIRECT, Family.RET_CC, 0xD8, 1, 2, 3,(int...parameters)->"RET C"),
    RST_0(Kind.DIRECT, Family.RST_U3, 0xC7, 1, 4,(int...parameters)->"RST 0"),
    RST_1(Kind.DIRECT, Family.RST_U3, 0xCF, 1, 4,(int...parameters)->"RST 1"),
    RST_2(Kind.DIRECT, Family.RST_U3, 0xD7, 1, 4,(int...parameters)->"RST 2"),
    RST_3(Kind.DIRECT, Family.RST_U3, 0xDF, 1, 4,(int...parameters)->"RST 3"),
    RST_4(Kind.DIRECT, Family.RST_U3, 0xE7, 1, 4,(int...parameters)->"RST 4"),
    RST_5(Kind.DIRECT, Family.RST_U3, 0xEF, 1, 4,(int...parameters)->"RST 5"),
    RST_6(Kind.DIRECT, Family.RST_U3, 0xF7, 1, 4,(int...parameters)->"RST 6"),
    RST_7(Kind.DIRECT, Family.RST_U3, 0xFF, 1, 4,(int...parameters)->"RST 7"),
    LD_SP_HL(Kind.DIRECT, Family.LD_SP_HL, 0xF9, 1, 2,(int...parameters)->"LD SP,HL"),
    LD_A_HLRI(Kind.DIRECT, Family.LD_A_HLRU, 0x2A, 1, 2,(int...parameters)->"LD A,[HL+]"),
    LD_A_HLRD(Kind.DIRECT, Family.LD_A_HLRU, 0x3A, 1, 2,(int...parameters)->"LD A,[HL-]"),
    LD_A_BCR(Kind.DIRECT, Family.LD_A_BCR, 0x0A, 1, 2,(int...parameters)->"LD A,[BC]"),
    LD_A_DER(Kind.DIRECT, Family.LD_A_DER, 0x1A, 1, 2,(int...parameters)->"LD A,[DE]"),
    LD_A_CR(Kind.DIRECT, Family.LD_A_CR, 0xF2, 1, 2,(int...parameters)->"LD A,[$FF00+C]"),
    LD_HLRI_A(Kind.DIRECT, Family.LD_HLRU_A, 0x22, 1, 2,(int...parameters)->"LD [HL+],A"),
    LD_HLRD_A(Kind.DIRECT, Family.LD_HLRU_A, 0x32, 1, 2,(int...parameters)->"LD [HL-],A"),
    LD_BCR_A(Kind.DIRECT, Family.LD_BCR_A, 0x02, 1, 2,(int...parameters)->"LD [BC],A"),
    LD_DER_A(Kind.DIRECT, Family.LD_DER_A, 0x12, 1, 2,(int...parameters)->"LD [DE],A"),
    LD_CR_A(Kind.DIRECT, Family.LD_CR_A, 0xE2, 1, 2,(int...parameters)->"LD [$FF00+C],A"),
    JP_HL(Kind.DIRECT, Family.JP_HL, 0xE9, 1, 1,(int...parameters)->"JP [HL]"),
    RET(Kind.DIRECT, Family.RET, 0xC9, 1, 4,(int...parameters)->"RET"),
    RETI(Kind.DIRECT, Family.RETI, 0xD9, 1, 4,(int...parameters)->"RETI"),
    DAA(Kind.DIRECT, Family.DAA, 0x27, 1, 1,(int...parameters)->"DAA"),
    CPL(Kind.DIRECT, Family.CPL, 0x2F, 1, 1,(int...parameters)->"CPL"),
    NOP(Kind.DIRECT, Family.NOP, 0x00, 1, 1,(int...parameters)->"NOP"),
    HALT(Kind.DIRECT, Family.HALT, 0x76, 1, 0,(int...parameters)->"HALT"),
    STOP(Kind.DIRECT, Family.STOP, 0x10, 1, 0,(int...parameters)->"STOP"),
    CCF(Kind.DIRECT, Family.SCCF, 0x3F, 1, 1,(int...parameters)->"CCF"),
    SCF(Kind.DIRECT, Family.SCCF, 0x37, 1, 1,(int...parameters)->"SCF"),
    DI(Kind.DIRECT, Family.EDI, 0xF3, 1, 1,(int...parameters)->"DI"),
    EI(Kind.DIRECT, Family.EDI, 0xFB, 1, 1,(int...parameters)->"EI"),
    LD_A_N8R(Kind.DIRECT, Family.LD_A_N8R, 0xF0, 2, 3, (int...parameters)->"LD A, [$FF00 + "+ Integer.toHexString(parameters[0])+" ]"),
    LD_HL_SP_N8(Kind.DIRECT, Family.LD_HLSP_S8, 0xF8, 2, 3, (int...parameters)->"LD HL, SP+"+ Integer.toHexString(parameters[0])),
    LD_HLR_N8(Kind.DIRECT, Family.LD_HLR_N8, 0x36, 2, 3, (int...parameters)->"LD [HL], $"+ Integer.toHexString(parameters[0])),
    LD_N8R_A(Kind.DIRECT, Family.LD_N8R_A, 0xE0, 2, 3, (int...parameters)->"LD A, $"+ Integer.toHexString(parameters[0])),
    ADD_SP_N(Kind.DIRECT, Family.LD_HLSP_S8, 0xE8, 2, 4, (int...parameters)->"ADD SP, $"+ Integer.toHexString(parameters[0])),
    LD_A_N16R(Kind.DIRECT, Family.LD_A_N16R, 0xFA, 3, 4, (int...parameters)->"LD A, $"+Integer.toHexString((parameters[1]<<8)| parameters[0])),
    LD_N16R_A(Kind.DIRECT, Family.LD_N16R_A, 0xEA, 3, 4, (int...parameters)->"LD [$"+Integer.toHexString((parameters[1]<<8)| parameters[0])+"], A"),
    LD_N16R_SP(Kind.DIRECT, Family.LD_N16R_SP, 0x08, 3, 5, (int...parameters)->"LD [$ "+Integer.toHexString((parameters[1]<<8)| parameters[0])+"], SP"),
    JP_N16(Kind.DIRECT, Family.JP_N16, 0xC3, 3, 4, (int...parameters)->"JP [$" +Integer.toHexString((parameters[1]<<8)|parameters[0])+ "]"),
    CALL_N16(Kind.DIRECT, Family.CALL_N16, 0xCD, 3, 6, (int...parameters)->"CALL [$ "+Integer.toHexString((parameters[1]<<8)| parameters[0])+"]"),
    JR_E8(Kind.DIRECT, Family.JR_E8, 0x18, 2, 3, (int...parameters)->"JR "+ Integer.toHexString(parameters[0])),

    // Prefixed opcodes
    RLC_B(Kind.PREFIXED, Family.ROTC_R8, 0x00, 2, 2,(int...parameters)->"RLC B"),
    RLC_C(Kind.PREFIXED, Family.ROTC_R8, 0x01, 2, 2,(int...parameters)->"RLC C"),
    RLC_D(Kind.PREFIXED, Family.ROTC_R8, 0x02, 2, 2,(int...parameters)->"RLC D"),
    RLC_E(Kind.PREFIXED, Family.ROTC_R8, 0x03, 2, 2,(int...parameters)->"RLC E"),
    RLC_H(Kind.PREFIXED, Family.ROTC_R8, 0x04, 2, 2,(int...parameters)->"RLC H"),
    RLC_L(Kind.PREFIXED, Family.ROTC_R8, 0x05, 2, 2,(int...parameters)->"RLC L"),
    RLC_A(Kind.PREFIXED, Family.ROTC_R8, 0x07, 2, 2,(int...parameters)->"RLC A"),
    RRC_B(Kind.PREFIXED, Family.ROTC_R8, 0x08, 2, 2,(int...parameters)->"RRC B"),
    RRC_C(Kind.PREFIXED, Family.ROTC_R8, 0x09, 2, 2,(int...parameters)->"RRC C"),
    RRC_D(Kind.PREFIXED, Family.ROTC_R8, 0x0A, 2, 2,(int...parameters)->"RRC D"),
    RRC_E(Kind.PREFIXED, Family.ROTC_R8, 0x0B, 2, 2,(int...parameters)->"RRC E"),
    RRC_H(Kind.PREFIXED, Family.ROTC_R8, 0x0C, 2, 2,(int...parameters)->"RRC H"),
    RRC_L(Kind.PREFIXED, Family.ROTC_R8, 0x0D, 2, 2,(int...parameters)->"RRC L"),
    RRC_A(Kind.PREFIXED, Family.ROTC_R8, 0x0F, 2, 2,(int...parameters)->"RRC A"),
    RL_B(Kind.PREFIXED, Family.ROT_R8, 0x10, 2, 2,(int...parameters)->"RL B"),
    RL_C(Kind.PREFIXED, Family.ROT_R8, 0x11, 2, 2,(int...parameters)->"RL C"),
    RL_D(Kind.PREFIXED, Family.ROT_R8, 0x12, 2, 2,(int...parameters)->"RL D"),
    RL_E(Kind.PREFIXED, Family.ROT_R8, 0x13, 2, 2,(int...parameters)->"RL E"),
    RL_H(Kind.PREFIXED, Family.ROT_R8, 0x14, 2, 2,(int...parameters)->"RL H"),
    RL_L(Kind.PREFIXED, Family.ROT_R8, 0x15, 2, 2,(int...parameters)->"RL L"),
    RL_A(Kind.PREFIXED, Family.ROT_R8, 0x17, 2, 2,(int...parameters)->"RL A"),
    RR_B(Kind.PREFIXED, Family.ROT_R8, 0x18, 2, 2,(int...parameters)->"RR B"),
    RR_C(Kind.PREFIXED, Family.ROT_R8, 0x19, 2, 2,(int...parameters)->"RR C"),
    RR_D(Kind.PREFIXED, Family.ROT_R8, 0x1A, 2, 2,(int...parameters)->"RR D"),
    RR_E(Kind.PREFIXED, Family.ROT_R8, 0x1B, 2, 2,(int...parameters)->"RR E"),
    RR_H(Kind.PREFIXED, Family.ROT_R8, 0x1C, 2, 2,(int...parameters)->"RR H"),
    RR_L(Kind.PREFIXED, Family.ROT_R8, 0x1D, 2, 2,(int...parameters)->"RR L"),
    RR_A(Kind.PREFIXED, Family.ROT_R8, 0x1F, 2, 2,(int...parameters)->"RR A"),
    SLA_B(Kind.PREFIXED, Family.SLA_R8, 0x20, 2, 2,(int...parameters)->"SLA B"),
    SLA_C(Kind.PREFIXED, Family.SLA_R8, 0x21, 2, 2,(int...parameters)->"SLA C"),
    SLA_D(Kind.PREFIXED, Family.SLA_R8, 0x22, 2, 2,(int...parameters)->"SLA D"),
    SLA_E(Kind.PREFIXED, Family.SLA_R8, 0x23, 2, 2,(int...parameters)->"SLA E"),
    SLA_H(Kind.PREFIXED, Family.SLA_R8, 0x24, 2, 2,(int...parameters)->"SLA H"),
    SLA_L(Kind.PREFIXED, Family.SLA_R8, 0x25, 2, 2,(int...parameters)->"SLA L"),
    SLA_A(Kind.PREFIXED, Family.SLA_R8, 0x27, 2, 2,(int...parameters)->"SLA A"),
    SRA_B(Kind.PREFIXED, Family.SRA_R8, 0x28, 2, 2,(int...parameters)->"SRA B"),
    SRA_C(Kind.PREFIXED, Family.SRA_R8, 0x29, 2, 2,(int...parameters)->"SRA C"),
    SRA_D(Kind.PREFIXED, Family.SRA_R8, 0x2A, 2, 2,(int...parameters)->"SRA D"),
    SRA_E(Kind.PREFIXED, Family.SRA_R8, 0x2B, 2, 2,(int...parameters)->"SRA E"),
    SRA_H(Kind.PREFIXED, Family.SRA_R8, 0x2C, 2, 2,(int...parameters)->"SRA H"),
    SRA_L(Kind.PREFIXED, Family.SRA_R8, 0x2D, 2, 2,(int...parameters)->"SRA L"),
    SRA_A(Kind.PREFIXED, Family.SRA_R8, 0x2F, 2, 2,(int...parameters)->"SRA A"),
    SWAP_B(Kind.PREFIXED, Family.SWAP_R8, 0x30, 2, 2,(int...parameters)->"SWAP B"),
    SWAP_C(Kind.PREFIXED, Family.SWAP_R8, 0x31, 2, 2,(int...parameters)->"SWAP C"),
    SWAP_D(Kind.PREFIXED, Family.SWAP_R8, 0x32, 2, 2,(int...parameters)->"SWAP D"),
    SWAP_E(Kind.PREFIXED, Family.SWAP_R8, 0x33, 2, 2,(int...parameters)->"SWAP E"),
    SWAP_H(Kind.PREFIXED, Family.SWAP_R8, 0x34, 2, 2,(int...parameters)->"SWAP H"),
    SWAP_L(Kind.PREFIXED, Family.SWAP_R8, 0x35, 2, 2,(int...parameters)->"SWAP L"),
    SWAP_A(Kind.PREFIXED, Family.SWAP_R8, 0x37, 2, 2,(int...parameters)->"SWAP A"),
    SRL_B(Kind.PREFIXED, Family.SRL_R8, 0x38, 2, 2,(int...parameters)->"SRL B"),
    SRL_C(Kind.PREFIXED, Family.SRL_R8, 0x39, 2, 2,(int...parameters)->"SRL C"),
    SRL_D(Kind.PREFIXED, Family.SRL_R8, 0x3A, 2, 2,(int...parameters)->"SRL D"),
    SRL_E(Kind.PREFIXED, Family.SRL_R8, 0x3B, 2, 2,(int...parameters)->"SRL E"),
    SRL_H(Kind.PREFIXED, Family.SRL_R8, 0x3C, 2, 2,(int...parameters)->"SRL H"),
    SRL_L(Kind.PREFIXED, Family.SRL_R8, 0x3D, 2, 2,(int...parameters)->"SRL L"),
    SRL_A(Kind.PREFIXED, Family.SRL_R8, 0x3F, 2, 2,(int...parameters)->"SRL A"),
    RLC_HLR(Kind.PREFIXED, Family.ROTC_HLR, 0x06, 2, 4,(int...parameters)->"RLC [HL]"),
    RRC_HLR(Kind.PREFIXED, Family.ROTC_HLR, 0x0E, 2, 4,(int...parameters)->"RRC [HL]"),
    RL_HLR(Kind.PREFIXED, Family.ROT_HLR, 0x16, 2, 4,(int...parameters)->"RL [HL]"),
    RR_HLR(Kind.PREFIXED, Family.ROT_HLR, 0x1E, 2, 4,(int...parameters)->"RR [HL]"),
    SLA_HLR(Kind.PREFIXED, Family.SLA_HLR, 0x26, 2, 4,(int...parameters)->"SLA [HL]"),
    SRA_HLR(Kind.PREFIXED, Family.SRA_HLR, 0x2E, 2, 4,(int...parameters)->"SRA [HL]"),
    SWAP_HLR(Kind.PREFIXED, Family.SWAP_HLR, 0x36, 2, 4,(int...parameters)->"SWAP [HL]"),
    SRL_HLR(Kind.PREFIXED, Family.SRL_HLR, 0x3E, 2, 4,(int...parameters)->"SRL [HL]"),
    BIT_0_B(Kind.PREFIXED, Family.BIT_U3_R8, 0x40, 2, 2,(int...parameters)->"BIT 0,B"),
    BIT_0_C(Kind.PREFIXED, Family.BIT_U3_R8, 0x41, 2, 2,(int...parameters)->"BIT 0,C"),
    BIT_0_D(Kind.PREFIXED, Family.BIT_U3_R8, 0x42, 2, 2,(int...parameters)->"BIT 0,D"),
    BIT_0_E(Kind.PREFIXED, Family.BIT_U3_R8, 0x43, 2, 2,(int...parameters)->"BIT 0,E"),
    BIT_0_H(Kind.PREFIXED, Family.BIT_U3_R8, 0x44, 2, 2,(int...parameters)->"BIT 0,H"),
    BIT_0_L(Kind.PREFIXED, Family.BIT_U3_R8, 0x45, 2, 2,(int...parameters)->"BIT 0,L"),
    BIT_0_A(Kind.PREFIXED, Family.BIT_U3_R8, 0x47, 2, 2,(int...parameters)->"BIT 0,A"),
    BIT_1_B(Kind.PREFIXED, Family.BIT_U3_R8, 0x48, 2, 2,(int...parameters)->"BIT 1,B"),
    BIT_1_C(Kind.PREFIXED, Family.BIT_U3_R8, 0x49, 2, 2,(int...parameters)->"BIT 1,C"),
    BIT_1_D(Kind.PREFIXED, Family.BIT_U3_R8, 0x4A, 2, 2,(int...parameters)->"BIT 1,D"),
    BIT_1_E(Kind.PREFIXED, Family.BIT_U3_R8, 0x4B, 2, 2,(int...parameters)->"BIT 1,E"),
    BIT_1_H(Kind.PREFIXED, Family.BIT_U3_R8, 0x4C, 2, 2,(int...parameters)->"BIT 1,H"),
    BIT_1_L(Kind.PREFIXED, Family.BIT_U3_R8, 0x4D, 2, 2,(int...parameters)->"BIT 1,L"),
    BIT_1_A(Kind.PREFIXED, Family.BIT_U3_R8, 0x4F, 2, 2,(int...parameters)->"BIT 1,A"),
    BIT_2_B(Kind.PREFIXED, Family.BIT_U3_R8, 0x50, 2, 2,(int...parameters)->"BIT 2,B"),
    BIT_2_C(Kind.PREFIXED, Family.BIT_U3_R8, 0x51, 2, 2,(int...parameters)->"BIT 2,C"),
    BIT_2_D(Kind.PREFIXED, Family.BIT_U3_R8, 0x52, 2, 2,(int...parameters)->"BIT 2,D"),
    BIT_2_E(Kind.PREFIXED, Family.BIT_U3_R8, 0x53, 2, 2,(int...parameters)->"BIT 2,E"),
    BIT_2_H(Kind.PREFIXED, Family.BIT_U3_R8, 0x54, 2, 2,(int...parameters)->"BIT 2,H"),
    BIT_2_L(Kind.PREFIXED, Family.BIT_U3_R8, 0x55, 2, 2,(int...parameters)->"BIT 2,L"),
    BIT_2_A(Kind.PREFIXED, Family.BIT_U3_R8, 0x57, 2, 2,(int...parameters)->"BIT 2,A"),
    BIT_3_B(Kind.PREFIXED, Family.BIT_U3_R8, 0x58, 2, 2,(int...parameters)->"BIT 3,B"),
    BIT_3_C(Kind.PREFIXED, Family.BIT_U3_R8, 0x59, 2, 2,(int...parameters)->"BIT 3,C"),
    BIT_3_D(Kind.PREFIXED, Family.BIT_U3_R8, 0x5A, 2, 2,(int...parameters)->"BIT 3,D"),
    BIT_3_E(Kind.PREFIXED, Family.BIT_U3_R8, 0x5B, 2, 2,(int...parameters)->"BIT 3,E"),
    BIT_3_H(Kind.PREFIXED, Family.BIT_U3_R8, 0x5C, 2, 2,(int...parameters)->"BIT 3,H"),
    BIT_3_L(Kind.PREFIXED, Family.BIT_U3_R8, 0x5D, 2, 2,(int...parameters)->"BIT 3,L"),
    BIT_3_A(Kind.PREFIXED, Family.BIT_U3_R8, 0x5F, 2, 2,(int...parameters)->"BIT 3,A"),
    BIT_4_B(Kind.PREFIXED, Family.BIT_U3_R8, 0x60, 2, 2,(int...parameters)->"BIT 4,B"),
    BIT_4_C(Kind.PREFIXED, Family.BIT_U3_R8, 0x61, 2, 2,(int...parameters)->"BIT 4,C"),
    BIT_4_D(Kind.PREFIXED, Family.BIT_U3_R8, 0x62, 2, 2,(int...parameters)->"BIT 4,D"),
    BIT_4_E(Kind.PREFIXED, Family.BIT_U3_R8, 0x63, 2, 2,(int...parameters)->"BIT 4,E"),
    BIT_4_H(Kind.PREFIXED, Family.BIT_U3_R8, 0x64, 2, 2,(int...parameters)->"BIT 4,H"),
    BIT_4_L(Kind.PREFIXED, Family.BIT_U3_R8, 0x65, 2, 2,(int...parameters)->"BIT 4,L"),
    BIT_4_A(Kind.PREFIXED, Family.BIT_U3_R8, 0x67, 2, 2,(int...parameters)->"BIT 4,A"),
    BIT_5_B(Kind.PREFIXED, Family.BIT_U3_R8, 0x68, 2, 2,(int...parameters)->"BIT 5,B"),
    BIT_5_C(Kind.PREFIXED, Family.BIT_U3_R8, 0x69, 2, 2,(int...parameters)->"BIT 5,C"),
    BIT_5_D(Kind.PREFIXED, Family.BIT_U3_R8, 0x6A, 2, 2,(int...parameters)->"BIT 5,D"),
    BIT_5_E(Kind.PREFIXED, Family.BIT_U3_R8, 0x6B, 2, 2,(int...parameters)->"BIT 5,E"),
    BIT_5_H(Kind.PREFIXED, Family.BIT_U3_R8, 0x6C, 2, 2,(int...parameters)->"BIT 5,H"),
    BIT_5_L(Kind.PREFIXED, Family.BIT_U3_R8, 0x6D, 2, 2,(int...parameters)->"BIT 5,L"),
    BIT_5_A(Kind.PREFIXED, Family.BIT_U3_R8, 0x6F, 2, 2,(int...parameters)->"BIT 5,A"),
    BIT_6_B(Kind.PREFIXED, Family.BIT_U3_R8, 0x70, 2, 2,(int...parameters)->"BIT 6,B"),
    BIT_6_C(Kind.PREFIXED, Family.BIT_U3_R8, 0x71, 2, 2,(int...parameters)->"BIT 6,C"),
    BIT_6_D(Kind.PREFIXED, Family.BIT_U3_R8, 0x72, 2, 2,(int...parameters)->"BIT 6,D"),
    BIT_6_E(Kind.PREFIXED, Family.BIT_U3_R8, 0x73, 2, 2,(int...parameters)->"BIT 6,E"),
    BIT_6_H(Kind.PREFIXED, Family.BIT_U3_R8, 0x74, 2, 2,(int...parameters)->"BIT 6,H"),
    BIT_6_L(Kind.PREFIXED, Family.BIT_U3_R8, 0x75, 2, 2,(int...parameters)->"BIT 6,L"),
    BIT_6_A(Kind.PREFIXED, Family.BIT_U3_R8, 0x77, 2, 2,(int...parameters)->"BIT 6,A"),
    BIT_7_B(Kind.PREFIXED, Family.BIT_U3_R8, 0x78, 2, 2,(int...parameters)->"BIT 7,B"),
    BIT_7_C(Kind.PREFIXED, Family.BIT_U3_R8, 0x79, 2, 2,(int...parameters)->"BIT 7,C"),
    BIT_7_D(Kind.PREFIXED, Family.BIT_U3_R8, 0x7A, 2, 2,(int...parameters)->"BIT 7,D"),
    BIT_7_E(Kind.PREFIXED, Family.BIT_U3_R8, 0x7B, 2, 2,(int...parameters)->"BIT 7,E"),
    BIT_7_H(Kind.PREFIXED, Family.BIT_U3_R8, 0x7C, 2, 2,(int...parameters)->"BIT 7,H"),
    BIT_7_L(Kind.PREFIXED, Family.BIT_U3_R8, 0x7D, 2, 2,(int...parameters)->"BIT 7,L"),
    BIT_7_A(Kind.PREFIXED, Family.BIT_U3_R8, 0x7F, 2, 2,(int...parameters)->"BIT 7,A"),
    RES_0_B(Kind.PREFIXED, Family.CHG_U3_R8, 0x80, 2, 2,(int...parameters)->"RES 0,B"),
    RES_0_C(Kind.PREFIXED, Family.CHG_U3_R8, 0x81, 2, 2,(int...parameters)->"RES 0,C"),
    RES_0_D(Kind.PREFIXED, Family.CHG_U3_R8, 0x82, 2, 2,(int...parameters)->"RES 0,D"),
    RES_0_E(Kind.PREFIXED, Family.CHG_U3_R8, 0x83, 2, 2,(int...parameters)->"RES 0,E"),
    RES_0_H(Kind.PREFIXED, Family.CHG_U3_R8, 0x84, 2, 2,(int...parameters)->"RES 0,H"),
    RES_0_L(Kind.PREFIXED, Family.CHG_U3_R8, 0x85, 2, 2,(int...parameters)->"RES 0,L"),
    RES_0_A(Kind.PREFIXED, Family.CHG_U3_R8, 0x87, 2, 2,(int...parameters)->"RES 0,A"),
    RES_1_B(Kind.PREFIXED, Family.CHG_U3_R8, 0x88, 2, 2,(int...parameters)->"RES 1,B"),
    RES_1_C(Kind.PREFIXED, Family.CHG_U3_R8, 0x89, 2, 2,(int...parameters)->"RES 1,C"),
    RES_1_D(Kind.PREFIXED, Family.CHG_U3_R8, 0x8A, 2, 2,(int...parameters)->"RES 1,D"),
    RES_1_E(Kind.PREFIXED, Family.CHG_U3_R8, 0x8B, 2, 2,(int...parameters)->"RES 1,E"),
    RES_1_H(Kind.PREFIXED, Family.CHG_U3_R8, 0x8C, 2, 2,(int...parameters)->"RES 1,H"),
    RES_1_L(Kind.PREFIXED, Family.CHG_U3_R8, 0x8D, 2, 2,(int...parameters)->"RES 1,L"),
    RES_1_A(Kind.PREFIXED, Family.CHG_U3_R8, 0x8F, 2, 2,(int...parameters)->"RES 1,A"),
    RES_2_B(Kind.PREFIXED, Family.CHG_U3_R8, 0x90, 2, 2,(int...parameters)->"RES 2,B"),
    RES_2_C(Kind.PREFIXED, Family.CHG_U3_R8, 0x91, 2, 2,(int...parameters)->"RES 2,C"),
    RES_2_D(Kind.PREFIXED, Family.CHG_U3_R8, 0x92, 2, 2,(int...parameters)->"RES 2,D"),
    RES_2_E(Kind.PREFIXED, Family.CHG_U3_R8, 0x93, 2, 2,(int...parameters)->"RES 2,E"),
    RES_2_H(Kind.PREFIXED, Family.CHG_U3_R8, 0x94, 2, 2,(int...parameters)->"RES 2,H"),
    RES_2_L(Kind.PREFIXED, Family.CHG_U3_R8, 0x95, 2, 2,(int...parameters)->"RES 2,L"),
    RES_2_A(Kind.PREFIXED, Family.CHG_U3_R8, 0x97, 2, 2,(int...parameters)->"RES 2,A"),
    RES_3_B(Kind.PREFIXED, Family.CHG_U3_R8, 0x98, 2, 2,(int...parameters)->"RES 3,B"),
    RES_3_C(Kind.PREFIXED, Family.CHG_U3_R8, 0x99, 2, 2,(int...parameters)->"RES 3,C"),
    RES_3_D(Kind.PREFIXED, Family.CHG_U3_R8, 0x9A, 2, 2,(int...parameters)->"RES 3,D"),
    RES_3_E(Kind.PREFIXED, Family.CHG_U3_R8, 0x9B, 2, 2,(int...parameters)->"RES 3,E"),
    RES_3_H(Kind.PREFIXED, Family.CHG_U3_R8, 0x9C, 2, 2,(int...parameters)->"RES 3,H"),
    RES_3_L(Kind.PREFIXED, Family.CHG_U3_R8, 0x9D, 2, 2,(int...parameters)->"RES 3,L"),
    RES_3_A(Kind.PREFIXED, Family.CHG_U3_R8, 0x9F, 2, 2,(int...parameters)->"RES 3,A"),
    RES_4_B(Kind.PREFIXED, Family.CHG_U3_R8, 0xA0, 2, 2,(int...parameters)->"RES 4,B"),
    RES_4_C(Kind.PREFIXED, Family.CHG_U3_R8, 0xA1, 2, 2,(int...parameters)->"RES 4,C"),
    RES_4_D(Kind.PREFIXED, Family.CHG_U3_R8, 0xA2, 2, 2,(int...parameters)->"RES 4,D"),
    RES_4_E(Kind.PREFIXED, Family.CHG_U3_R8, 0xA3, 2, 2,(int...parameters)->"RES 4,E"),
    RES_4_H(Kind.PREFIXED, Family.CHG_U3_R8, 0xA4, 2, 2,(int...parameters)->"RES 4,H"),
    RES_4_L(Kind.PREFIXED, Family.CHG_U3_R8, 0xA5, 2, 2,(int...parameters)->"RES 4,L"),
    RES_4_A(Kind.PREFIXED, Family.CHG_U3_R8, 0xA7, 2, 2,(int...parameters)->"RES 4,A"),
    RES_5_B(Kind.PREFIXED, Family.CHG_U3_R8, 0xA8, 2, 2,(int...parameters)->"RES 5,B"),
    RES_5_C(Kind.PREFIXED, Family.CHG_U3_R8, 0xA9, 2, 2,(int...parameters)->"RES 5,C"),
    RES_5_D(Kind.PREFIXED, Family.CHG_U3_R8, 0xAA, 2, 2,(int...parameters)->"RES 5,D"),
    RES_5_E(Kind.PREFIXED, Family.CHG_U3_R8, 0xAB, 2, 2,(int...parameters)->"RES 5,E"),
    RES_5_H(Kind.PREFIXED, Family.CHG_U3_R8, 0xAC, 2, 2,(int...parameters)->"RES 5,H"),
    RES_5_L(Kind.PREFIXED, Family.CHG_U3_R8, 0xAD, 2, 2,(int...parameters)->"RES 5,L"),
    RES_5_A(Kind.PREFIXED, Family.CHG_U3_R8, 0xAF, 2, 2,(int...parameters)->"RES 5,A"),
    RES_6_B(Kind.PREFIXED, Family.CHG_U3_R8, 0xB0, 2, 2,(int...parameters)->"RES 6,B"),
    RES_6_C(Kind.PREFIXED, Family.CHG_U3_R8, 0xB1, 2, 2,(int...parameters)->"RES 6,C"),
    RES_6_D(Kind.PREFIXED, Family.CHG_U3_R8, 0xB2, 2, 2,(int...parameters)->"RES 6,D"),
    RES_6_E(Kind.PREFIXED, Family.CHG_U3_R8, 0xB3, 2, 2,(int...parameters)->"RES 6,E"),
    RES_6_H(Kind.PREFIXED, Family.CHG_U3_R8, 0xB4, 2, 2,(int...parameters)->"RES 6,H"),
    RES_6_A(Kind.PREFIXED, Family.CHG_U3_R8, 0xB7, 2, 2,(int...parameters)->"RES 6,A"),
    RES_7_B(Kind.PREFIXED, Family.CHG_U3_R8, 0xB8, 2, 2,(int...parameters)->"RES 7,B"),
    RES_7_C(Kind.PREFIXED, Family.CHG_U3_R8, 0xB9, 2, 2,(int...parameters)->"RES 7,C"),
    RES_7_D(Kind.PREFIXED, Family.CHG_U3_R8, 0xBA, 2, 2,(int...parameters)->"RES 7,D"),
    RES_7_E(Kind.PREFIXED, Family.CHG_U3_R8, 0xBB, 2, 2,(int...parameters)->"RES 7,E"),
    RES_7_H(Kind.PREFIXED, Family.CHG_U3_R8, 0xBC, 2, 2,(int...parameters)->"RES 7,H"),
    RES_7_L(Kind.PREFIXED, Family.CHG_U3_R8, 0xBD, 2, 2,(int...parameters)->"RES 7,L"),
    RES_7_A(Kind.PREFIXED, Family.CHG_U3_R8, 0xBF, 2, 2,(int...parameters)->"RES 7,A"),
    SET_0_B(Kind.PREFIXED, Family.CHG_U3_R8, 0xC0, 2, 2,(int...parameters)->"SET 0,B"),
    SET_0_C(Kind.PREFIXED, Family.CHG_U3_R8, 0xC1, 2, 2,(int...parameters)->"SET 0,C"),
    SET_0_D(Kind.PREFIXED, Family.CHG_U3_R8, 0xC2, 2, 2,(int...parameters)->"SET 0,D"),
    SET_0_E(Kind.PREFIXED, Family.CHG_U3_R8, 0xC3, 2, 2,(int...parameters)->"SET 0,E"),
    SET_0_H(Kind.PREFIXED, Family.CHG_U3_R8, 0xC4, 2, 2,(int...parameters)->"SET 0,H"),
    SET_0_L(Kind.PREFIXED, Family.CHG_U3_R8, 0xC5, 2, 2,(int...parameters)->"SET 0,L"),
    SET_0_A(Kind.PREFIXED, Family.CHG_U3_R8, 0xC7, 2, 2,(int...parameters)->"SET 0,A"),
    SET_1_B(Kind.PREFIXED, Family.CHG_U3_R8, 0xC8, 2, 2,(int...parameters)->"SET 1,B"),
    SET_1_C(Kind.PREFIXED, Family.CHG_U3_R8, 0xC9, 2, 2,(int...parameters)->"SET 1,C"),
    SET_1_D(Kind.PREFIXED, Family.CHG_U3_R8, 0xCA, 2, 2,(int...parameters)->"SET 1,D"),
    SET_1_E(Kind.PREFIXED, Family.CHG_U3_R8, 0xCB, 2, 2,(int...parameters)->"SET 1,E"),
    SET_1_H(Kind.PREFIXED, Family.CHG_U3_R8, 0xCC, 2, 2,(int...parameters)->"SET 1,H"),
    SET_1_L(Kind.PREFIXED, Family.CHG_U3_R8, 0xCD, 2, 2,(int...parameters)->"SET 1,L"),
    SET_1_A(Kind.PREFIXED, Family.CHG_U3_R8, 0xCF, 2, 2,(int...parameters)->"SET 1,A"),
    SET_2_B(Kind.PREFIXED, Family.CHG_U3_R8, 0xD0, 2, 2,(int...parameters)->"SET 2,B"),
    SET_2_C(Kind.PREFIXED, Family.CHG_U3_R8, 0xD1, 2, 2,(int...parameters)->"SET 2,C"),
    SET_2_D(Kind.PREFIXED, Family.CHG_U3_R8, 0xD2, 2, 2,(int...parameters)->"SET 2,D"),
    SET_2_E(Kind.PREFIXED, Family.CHG_U3_R8, 0xD3, 2, 2,(int...parameters)->"SET 2,E"),
    SET_2_H(Kind.PREFIXED, Family.CHG_U3_R8, 0xD4, 2, 2,(int...parameters)->"SET 2,H"),
    SET_2_L(Kind.PREFIXED, Family.CHG_U3_R8, 0xD5, 2, 2,(int...parameters)->"SET 2,L"),
    SET_2_A(Kind.PREFIXED, Family.CHG_U3_R8, 0xD7, 2, 2,(int...parameters)->"SET 2,A"),
    SET_3_B(Kind.PREFIXED, Family.CHG_U3_R8, 0xD8, 2, 2,(int...parameters)->"SET 3,B"),
    SET_3_C(Kind.PREFIXED, Family.CHG_U3_R8, 0xD9, 2, 2,(int...parameters)->"SET 3,C"),
    SET_3_D(Kind.PREFIXED, Family.CHG_U3_R8, 0xDA, 2, 2,(int...parameters)->"SET 3,D"),
    SET_3_E(Kind.PREFIXED, Family.CHG_U3_R8, 0xDB, 2, 2,(int...parameters)->"SET 3,E"),
    SET_3_H(Kind.PREFIXED, Family.CHG_U3_R8, 0xDC, 2, 2,(int...parameters)->"SET 3,H"),
    SET_3_L(Kind.PREFIXED, Family.CHG_U3_R8, 0xDD, 2, 2,(int...parameters)->"SET 3,L"),
    SET_3_A(Kind.PREFIXED, Family.CHG_U3_R8, 0xDF, 2, 2,(int...parameters)->"SET 3,A"),
    SET_4_B(Kind.PREFIXED, Family.CHG_U3_R8, 0xE0, 2, 2,(int...parameters)->"SET 4,B"),
    SET_4_C(Kind.PREFIXED, Family.CHG_U3_R8, 0xE1, 2, 2,(int...parameters)->"SET 4,C"),
    SET_4_D(Kind.PREFIXED, Family.CHG_U3_R8, 0xE2, 2, 2,(int...parameters)->"SET 4,D"),
    SET_4_E(Kind.PREFIXED, Family.CHG_U3_R8, 0xE3, 2, 2,(int...parameters)->"SET 4,E"),
    SET_4_H(Kind.PREFIXED, Family.CHG_U3_R8, 0xE4, 2, 2,(int...parameters)->"SET 4,H"),
    SET_4_L(Kind.PREFIXED, Family.CHG_U3_R8, 0xE5, 2, 2,(int...parameters)->"SET 4,L"),
    SET_4_A(Kind.PREFIXED, Family.CHG_U3_R8, 0xE7, 2, 2,(int...parameters)->"SET 4,A"),
    SET_5_B(Kind.PREFIXED, Family.CHG_U3_R8, 0xE8, 2, 2,(int...parameters)->"SET 5,B"),
    SET_5_C(Kind.PREFIXED, Family.CHG_U3_R8, 0xE9, 2, 2,(int...parameters)->"SET 5,C"),
    SET_5_D(Kind.PREFIXED, Family.CHG_U3_R8, 0xEA, 2, 2,(int...parameters)->"SET 5,D"),
    SET_5_E(Kind.PREFIXED, Family.CHG_U3_R8, 0xEB, 2, 2,(int...parameters)->"SET 5,E"),
    SET_5_H(Kind.PREFIXED, Family.CHG_U3_R8, 0xEC, 2, 2,(int...parameters)->"SET 5,H"),
    SET_5_L(Kind.PREFIXED, Family.CHG_U3_R8, 0xED, 2, 2,(int...parameters)->"SET 5,L"),
    SET_5_A(Kind.PREFIXED, Family.CHG_U3_R8, 0xEF, 2, 2,(int...parameters)->"SET 5,A"),
    SET_6_B(Kind.PREFIXED, Family.CHG_U3_R8, 0xF0, 2, 2,(int...parameters)->"SET 6,B"),
    SET_6_C(Kind.PREFIXED, Family.CHG_U3_R8, 0xF1, 2, 2,(int...parameters)->"SET 6,C"),
    SET_6_D(Kind.PREFIXED, Family.CHG_U3_R8, 0xF2, 2, 2,(int...parameters)->"SET 6,D"),
    SET_6_E(Kind.PREFIXED, Family.CHG_U3_R8, 0xF3, 2, 2,(int...parameters)->"SET 6,E"),
    SET_6_H(Kind.PREFIXED, Family.CHG_U3_R8, 0xF4, 2, 2,(int...parameters)->"SET 6,H"),
    SET_6_L(Kind.PREFIXED, Family.CHG_U3_R8, 0xF5, 2, 2,(int...parameters)->"SET 6,L"),
    SET_6_A(Kind.PREFIXED, Family.CHG_U3_R8, 0xF7, 2, 2,(int...parameters)->"SET 6,A"),
    SET_7_B(Kind.PREFIXED, Family.CHG_U3_R8, 0xF8, 2, 2,(int...parameters)->"SET 7,B"),
    SET_7_C(Kind.PREFIXED, Family.CHG_U3_R8, 0xF9, 2, 2,(int...parameters)->"SET 7,C"),
    SET_7_D(Kind.PREFIXED, Family.CHG_U3_R8, 0xFA, 2, 2,(int...parameters)->"SET 7,D"),
    SET_7_E(Kind.PREFIXED, Family.CHG_U3_R8, 0xFB, 2, 2,(int...parameters)->"SET 7,E"),
    SET_7_H(Kind.PREFIXED, Family.CHG_U3_R8, 0xFC, 2, 2,(int...parameters)->"SET 7,H"),
    SET_7_L(Kind.PREFIXED, Family.CHG_U3_R8, 0xFD, 2, 2,(int...parameters)->"SET 7,L"),
    SET_7_A(Kind.PREFIXED, Family.CHG_U3_R8, 0xFF, 2, 2,(int...parameters)->"SET 7,A"),
    BIT_0_HLR(Kind.PREFIXED, Family.BIT_U3_HLR, 0x46, 2, 3,(int...parameters)->"BIT 0,[HL]"),
    BIT_1_HLR(Kind.PREFIXED, Family.BIT_U3_HLR, 0x4E, 2, 3,(int...parameters)->"BIT 1,[HL]"),
    BIT_2_HLR(Kind.PREFIXED, Family.BIT_U3_HLR, 0x56, 2, 3,(int...parameters)->"BIT 2,[HL]"),
    BIT_3_HLR(Kind.PREFIXED, Family.BIT_U3_HLR, 0x5E, 2, 3,(int...parameters)->"BIT 3,[HL]"),
    BIT_4_HLR(Kind.PREFIXED, Family.BIT_U3_HLR, 0x66, 2, 3,(int...parameters)->"BIT 4,[HL]"),
    BIT_5_HLR(Kind.PREFIXED, Family.BIT_U3_HLR, 0x6E, 2, 3,(int...parameters)->"BIT 5,[HL]"),
    BIT_6_HLR(Kind.PREFIXED, Family.BIT_U3_HLR, 0x76, 2, 3,(int...parameters)->"BIT 6,[HL]"),
    BIT_7_HLR(Kind.PREFIXED, Family.BIT_U3_HLR, 0x7E, 2, 3,(int...parameters)->"BIT 7,[HL]"),
    RES_0_HLR(Kind.PREFIXED, Family.CHG_U3_HLR, 0x86, 2, 4,(int...parameters)->"RES 0,[HL]"),
    RES_1_HLR(Kind.PREFIXED, Family.CHG_U3_HLR, 0x8E, 2, 4,(int...parameters)->"RES 1,[HL]"),
    RES_2_HLR(Kind.PREFIXED, Family.CHG_U3_HLR, 0x96, 2, 4,(int...parameters)->"RES 2,[HL]"),
    RES_3_HLR(Kind.PREFIXED, Family.CHG_U3_HLR, 0x9E, 2, 4,(int...parameters)->"RES 3,[HL]"),
    RES_4_HLR(Kind.PREFIXED, Family.CHG_U3_HLR, 0xA6, 2, 4,(int...parameters)->"RES 4,[HL]"),
    RES_5_HLR(Kind.PREFIXED, Family.CHG_U3_HLR, 0xAE, 2, 4,(int...parameters)->"RES 5,[HL]"),
    RES_6_HLR(Kind.PREFIXED, Family.CHG_U3_HLR, 0xB6, 2, 4,(int...parameters)->"RES 6,[HL]"),
    RES_7_HLR(Kind.PREFIXED, Family.CHG_U3_HLR, 0xBE, 2, 4,(int...parameters)->"RES 7,[HL]"),
    SET_0_HLR(Kind.PREFIXED, Family.CHG_U3_HLR, 0xC6, 2, 4,(int...parameters)->"SET 0,[HL]"),
    SET_1_HLR(Kind.PREFIXED, Family.CHG_U3_HLR, 0xCE, 2, 4,(int...parameters)->"SET 1,[HL]"),
    SET_2_HLR(Kind.PREFIXED, Family.CHG_U3_HLR, 0xD6, 2, 4,(int...parameters)->"SET 2,[HL]"),
    SET_3_HLR(Kind.PREFIXED, Family.CHG_U3_HLR, 0xDE, 2, 4,(int...parameters)->"SET 3,[HL]"),
    SET_4_HLR(Kind.PREFIXED, Family.CHG_U3_HLR, 0xE6, 2, 4,(int...parameters)->"SET 4,[HL]"),
    SET_5_HLR(Kind.PREFIXED, Family.CHG_U3_HLR, 0xEE, 2, 4,(int...parameters)->"SET 5,[HL]"),
    SET_6_HLR(Kind.PREFIXED, Family.CHG_U3_HLR, 0xF6, 2, 4,(int...parameters)->"SET 6,[HL]"),
    SET_7_HLR(Kind.PREFIXED, Family.CHG_U3_HLR, 0xFE, 2, 4,(int...parameters)->"SET 7,[HL]");

    public enum Kind { DIRECT, PREFIXED }
    public enum Family {
        NOP,

        // Load
        LD_R8_HLR,
        LD_A_HLRU,
        LD_A_N8R,
        LD_A_CR,
        LD_A_N16R,
        LD_A_BCR,
        LD_A_DER,
        LD_R8_N8,
        LD_R16SP_N16,
        POP_R16,

        // Store
        LD_HLR_R8,
        LD_HLRU_A,
        LD_N8R_A,
        LD_CR_A,
        LD_N16R_A,
        LD_BCR_A,
        LD_DER_A,
        LD_HLR_N8,
        LD_N16R_SP,
        PUSH_R16,

        // Move
        LD_R8_R8,
        LD_SP_HL,

        // Add
        ADD_A_R8,
        ADD_A_N8,
        ADD_A_HLR,
        INC_R8,
        INC_HLR,
        INC_R16SP,
        ADD_HL_R16SP,
        LD_HLSP_S8,

        // Subtract / compare
        SUB_A_R8,
        SUB_A_N8,
        SUB_A_HLR,
        DEC_R8,
        DEC_HLR,
        CP_A_R8,
        CP_A_N8,
        CP_A_HLR,
        DEC_R16SP,

        // And
        AND_A_N8,
        AND_A_R8,
        AND_A_HLR,

        // (Inclusive) or
        OR_A_R8,
        OR_A_N8,
        OR_A_HLR,

        // Exclusive or
        XOR_A_R8,
        XOR_A_N8,
        XOR_A_HLR,

        // Rotate
        ROTCA,
        ROTA,
        ROTC_R8,
        ROT_R8,
        ROTC_HLR,
        ROT_HLR,
        SWAP_R8,
        SWAP_HLR,

        // Shift
        SLA_R8,
        SRA_R8,
        SRL_R8,
        SLA_HLR,
        SRA_HLR,
        SRL_HLR,

        // Bit test and (re)set
        BIT_U3_R8,
        BIT_U3_HLR,
        CHG_U3_R8,
        CHG_U3_HLR,

        // Miscellaneous ALU operations
        DAA,
        CPL,
        SCCF,

        // Jumps
        JP_HL,
        JP_N16,
        JP_CC_N16,
        JR_E8,
        JR_CC_E8,

        // Procedure call and return
        CALL_N16,
        CALL_CC_N16,
        RST_U3,
        RET,
        RET_CC,

        // Interrupt handling
        EDI,
        RETI,

        // Miscellaneous control instructions
        HALT,
        STOP
    }

    public final Kind kind;
    public final Family family;
    public final int encoding;
    public final int totalBytes;
    public final int cycles, additionalCycles;
    
    private final VariableStringFunction  representation ;

    private Opcode(Kind kind, Family family, int encoding, int totalBytes, int cycles, int additionalCycles, VariableStringFunction function) {
        this.kind = kind;
        this.family = family;
        this.encoding = encoding;
        this.totalBytes = totalBytes;
        this.cycles = cycles;
        this.additionalCycles = additionalCycles;
        this.representation=function;
    }
    
    private Opcode(Kind kind, Family family, int encoding, int totalBytes, int cycles, VariableStringFunction function) {
        this(kind, family, encoding, totalBytes, cycles, 0, function);
    }
    
    
    
    public String getString( int... parameters) {
        return representation.getString(parameters);
    }
    
    @FunctionalInterface
    interface VariableStringFunction {
        String getString( int... parameters);
    }
}
